### ISSUE TITLE
Quite there. But no internet access

### ISSUE THREAD

**Issue by adamantino** [rudiratlos/hotspot#1]
Hi, your script is amazing. Because of the many problems RPI 3B+ is experiencing with hostapd these kind of scripts are the real gems. Anyway, i set up everything and started the service, which seems to work. I'm able to see the hotspot from my device and connect. An IP is assigned, ... 
The only problem is that i'm not able to access the internet, which is weird because as you can see at the top of the screenshot a little bit of traffic (0.42kb/s) is transmitted.
Am i missing something?
RPI is connect to Ethernet and i'm using the internal wlan adaptor for the hotspot functionality (no external usb adaptor)   

![screenshot](https://i.ibb.co/FxJfx8b/Screenshot-20190116-104214-01.jpg "screenshot")

**Comment by rudiratlos** [comment]
do you have dhcp on ethernet side?

**Comment by adamantino** [comment]
yes i do, but the RPI gets a static IP (the one shown in picture), does it make a difference?
With my phone i'm connecting to the wifi generated by the RPI (which thanks to your script is configured to function as DHCP for its nat), so i don't get why the DHCP on the ethernet side should be a problem.

**Comment by adamantino** [comment]
Ok, i actually made it work by executing `hotspot modpar hostapd useiptables 1` which should be optional, but it seems mandatory for my case. Now it works as a AP. 
To turn on Tor do i have to manually route all TCP traffic from interface ap0 to port 9040? because i saw you commented out the PREROUTING in your script. just running `hotspot tor start` or `hotspot modpar hostapd torstart 1` and rebooting won't allow to reach any website.

**Comment by rudiratlos** [comment]
if you can reach the internet (routing ok for eth0<->ap0)
to use tor, just enable it. 
connect your client to hotspot wlan (ap0).
check tor, surf to:  https://check.torproject.org/

**Comment by rudiratlos** [comment]
Your ethernet ip adr can not be on the same subnet like ap0 (10.3.141.0/24).
configure your ethernet ip adr like 192.168.0.1
you need two differnet subnets. otherwise there will be no correct routing!
