### ISSUE TITLE
[closed] Problems accessing .local domain

### ISSUE THREAD

**Issue by marcusdiy** [rudiratlos/hotspot#10]
Hi, great script you got there! 
I've been using it at home for about 3 months...
But with the last updates something broke or maybe i misconfigured something else...
So the problem is that i cant connect to **home.local** anymore.
It seems to work only when rPi 3B+ is connected to LAN (cable).
If I disconnect it from LAN the address becomes unreacable.
I'm connecting via Android Chrome Browser. 
What can i do to make it work? Thanks!

**Comment by marcusdiy** [comment]
I got the old hotspot file: https://www.diffchecker.com/N7EniqHZ

**Comment by rudiratlos** [comment]
pls. do a 
hotspot setup

**Comment by rudiratlos** [comment]
I've change /etc/dnsmasq.conf
no-dhcp-interface=eth0,wlan0
listen-address=10.3.141.1
listen-address=127.0.0.1
to 
interface=ap0
this could be the problem.
I will change it back.

**Comment by marcusdiy** [comment]
Just done the full setup process with the last version...still not working.
Gonna try with a new rasbian image maybe i messed up something else...

**Comment by marcusdiy** [comment]
Guess what... now it works! Dunno why but it's ok :D

**Comment by marcusdiy** [comment]
Works on some devices i think that my testing phone was at fault
It's Xiaomi Redmi 5 Plus was working initially and then broke...still working on samsung
