### ISSUE TITLE
channel in hostapd

### ISSUE THREAD

**Issue by PA3DSS** [rudiratlos/hotspot#11]
I can not choose the channel i want, the script is changing hostapd.conf, why is  that ?
I can not choose which adapter i want to use, i would like to use an external wifi adapter, but with airmon-ng in kali linux shows all the time the MAC address of the internal wifi adapter.
But, this is by far the easiest script i found to install an AP , very nice !!

**Comment by PA3DSS** [comment]
I use an RPI3B+ , the latest raspbian lite strech, kernel:
uname -a
Linux 28 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux
I did a fresh install and withe the latest updates.
By the way, my external wifi adapters MAC address starts with 00:0f:00: , no need for install drivers.

**Comment by rudiratlos** [comment]
hotspot will choose the channel by itself. it tries to choose the best fitting channel (least used). 
hotspot will use the internal wlan device as hotspot. additional adapters (external wlan device or eth0) are used for internet connection.

**Comment by PA3DSS** [comment]
eth0 is for network, right, but an USB wifi antenna should be possible, the radio range is much much bigger!

**Comment by rudiratlos** [comment]
swapping ap0 to external wlan-adapter is to complicated/error-prone,
because hostapd.conf requires a definition for the driver (e.g. driver=rtl871xdrv).
to figure out which driver to use for every available usb-wlan-device is difficult. using the on board device is easy, because the driver is always nl80211

**Comment by PA3DSS** [comment]
Ok, thanks for your answer,  i assume that it is very complicated to 'grep' the current driver is installed.
Tonight i noticed an other issue with IP address, i make an other issue :)

**Comment by lquang4321** [comment]
Having a similar issue. So I guess it just chooses the least crowded channel regardless of frequency? I couldn't force 5Ghz since it just overwrites itself everytime I start.

**Comment by rudiratlos** [comment]
if you change the parameter ch_autofind to 0, hotspot will not modify the channel:
hotspot modpar self ch_autofind 0
