### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by PA3DSS** [rudiratlos/hotspot#13]
I noticed tonight that the static IP is back to DHCP after install hotspot.
What i have done, a clean fresh install on a RPI3b+ with all updates, make a static IP in dhcpcd.conf and rebooted to test if it is ok.
After the reboot i installed hotspot, and i noticed that the IP was changed of eth0, back to DHCP, why is that ? is there a way to use a static IP with hotspot ?
But i never seen a script that makes an AP so easy to install in such short time, it is really wonderfull !! thanks about it, nice work!!

**Comment by rudiratlos** [comment]
as you can see in the hotspot script, the file /etc/dhcpcd.conf will be overwritten at hotspot setup command. If you want a fixed ip adr for eth0 you can do 2 things:
1. (recomended) make a static entry mac-adr of eth0 with a fixed ip at your dhcp server on lan side. OR
2. (not recommended) adjust /etc/dhcpcd.conf on the pi thats running hotspot and do not rerun hotspot setup.

**Comment by PA3DSS** [comment]
ok thanks,  I understand, It's not that convenient, anyway thanks for your help !!

**Comment by jordeec** [comment]
> 1. (recomended) make a static entry mac-adr of eth0 with a fixed ip at your dhcp server on lan side. 

Could you please specify this a little?

**Comment by thotmail** [comment]
> > 1. (recomended) make a static entry mac-adr of eth0 with a fixed ip at your dhcp server on lan side.
> 
> Could you please specify this a little?

Instead of handling the static ip pi-side, do it on the other side of the ethernet cable ie. the router provided by the ISP usually has a DHCP reservation section where you can dictate the IP address that a particular mac address MUST be assigned

**Comment by jordeec** [comment]
Thanks for the clarification!
