### ISSUE TITLE
Connection problem when starting

### ISSUE THREAD

**Issue by marcusdiy** [rudiratlos/hotspot#16]
Hi, 
I'm using a raspberry pi 3b+ and maybe there is a problem.

If I connect to the WiFi just as soon it comes online, it will say connection error and will ask for the password again. If I wait for about 20 seconds once online it will work. Maybe the order of loading modules should be changed?

If I save the network, and keep the WiFi menu open, looking for a connection, and then start the hotspot the smartphone won't connect either. 

I got the same problem on different RPis, have you ever encountered similar problems?

**Comment by rudiratlos** [comment]
Hi,
during the startup, hotspot will try to find the least used channel. it uses iwlist commands after that we have process restarts of hostapd and dnsmasq. During the first ~20 seconds of hotspot startup, it could be that there is a hickup. Don't know if this is a problem. clients do reconnects.

**Comment by marcusdiy** [comment]
Yep, makes sense. Can I set the channel manually and disable the scan feature?
is `hotspot setchan 7` permanent?
