### ISSUE TITLE
Can connect only up to 10 devices?

### ISSUE THREAD

**Issue by marcusdiy** [rudiratlos/hotspot#17]
Hi, maybe this is a rather generic question but maybe you can help.
I'm using the stock hotspot script, i have some other iOT stuff in my house and i wanted to connect them to this Raspberry. So the problem is that i cant connect more than 10 devices, i duble checked the /etc/dnsmasq.conf and the range is right...it should allow theorically 149 devices...
`dhcp-range=10.3.141.50,10.3.141.199,255.255.255.0,12h`
If I disconnect one device, then i can connect another one, seems like an hard limit but i cant detect where it is set. I'm using a RPi 3 Model B+
Thanks as always

**Comment by rudiratlos** [comment]
do you have checked syslog for messages like:
"no leases left"

**Comment by rudiratlos** [comment]
could be this:
[https://www.raspberrypi.org/forums/viewtopic.php?t=210147](url)

**Comment by marcusdiy** [comment]
Yep what is happaning is pretty the same...
Will try to check the logs for "no leases left" once back at home

**Comment by martignoni** [comment]
Related: https://github.com/raspberrypi/linux/issues/3010

**Comment by marcusdiy** [comment]
Seems like every time, before reaching the quota, there is like some kind undervoltage issue...

Jul 28 20:49:07 dnsmasq-dhcp[896]: DHCPACK(ap0) 10.3.141.110 xx:xx:xx:xx:xx:xx HUAWEI_P9_lite
Jul 28 20:49:12 spherae kernel: [  440.556265] Under-voltage detected! (0x00050005)
Jul 28 20:49:16 spherae kernel: [  444.716262] Voltage normalised (0x00000000)
Jul 28 20:49:21 dnsmasq-dhcp[896]: DHCPDISCOVER(ap0) xx:xx:xx:xx:xx:xx
Jul 28 20:49:21 dnsmasq-dhcp[896]: DHCPOFFER(ap0) 10.3.141.108  xx:xx:xx:xx:xx:xx
Jul 28 20:49:21 dnsmasq-dhcp[896]: DHCPREQUEST(ap0) 10.3.141.108  xx:xx:xx:xx:xx:xx
Jul 28 20:49:21 dnsmasq-dhcp[896]: DHCPACK(ap0) 10.3.141.108  xx:xx:xx:xx:xx:xx Galaxy-S7
Jul 28 20:50:48 spherae kernel: [  536.727290] brcmfmac: send_key_to_dongle: wsec_key error (-52)

I'm using a duracell power bank rated for 2.4A
