### ISSUE TITLE
hostapd and dnsmasq not installed

### ISSUE THREAD

**Issue by InnoOmnia** [rudiratlos/hotspot#18]
I tried to install hotspot to Raspberry Pi 3 B+ with buster rasbian version.
When I issued this command 
hotspot setup
I got following error
ERROR:  hostapd is not installed (use hotspot setup)
Then I manually installed hostapd  and tried again command hotspot setup
now I got following error 
ERROR:  dnsmasq is not installed (use hotspot setup)
Then I manually installed dnsmasq  and tried agein  hotspot setup
Now it worked and continued to end.

Btw, thank you for very useful tool, I have been looking for long! 
I have small wish, I don't need TOR or VPN just this switching between WLAN AP/Client so if you could make that kind of version...

**Comment by rudiratlos** [comment]
just fixed the setup bug.
if you don't want to install ovpn and tor, prior to setup phase do:
hotspot modpar self aptaddinstlist ""
