### ISSUE TITLE
tor is not working

### ISSUE THREAD

**Issue by pettyP** [rudiratlos/hotspot#19]
hey,

i have successfully created a wifi to wifi  ( wlan0 and wlan1) access point with your tool. Everything is working fine i can connect to the access point with my smartphone and can access the internet. 

But as soon as i start the tor function my smartphone doesn't have a internet connection anymore. 

Does anybody else have the same problem???

**Comment by rudiratlos** [comment]
pls try the version from today. it uses firewalld instead of iptables. tor is working now
