### ISSUE TITLE
wlan0 doesnt support scanning : network is down

### ISSUE THREAD

**Issue by lovemussell** [rudiratlos/hotspot#2]
When I run hotspot start it overides my channel and hardware selection because the scanning fails. How can I turn off the FndChan function and have it only use the hostapd.conf parameters?

**Comment by rudiratlos** [comment]
I think that line 231 has to be changed (already done in V0.913)
from: Find_Chan $wli_dev 11
to:     Find_Chan "$wli_dev" "11"
