### ISSUE TITLE
external usb wlan adaptor

### ISSUE THREAD

**Issue by tempeet** [rudiratlos/hotspot#20]
Is it possible to use another external usb wlan adaptor-driver?
I use the mt7610u

Best regards
Peter

**Comment by rudiratlos** [comment]
yes, should work. hotspot is using always onboard wlan adapter for access point functionality. other working/active IP adapters (regardless if it is ethernet or other wlan usb adpater) are used for backend connection. Prerequisite is that your usb wlan adapter is already working (driver loaded ...)

**Comment by tempeet** [comment]
It works :-) Thanks!!!
But..... the wlan1 usb wifi stick lose connnection after one or two minutes..... and scanning is impossible. Any suggestions?

**Comment by rudiratlos** [comment]
pls. try your usb wlan adapter without hotspot. is your connection stable?

**Comment by tempeet** [comment]
On windows there is no problem. I tried the AC51 adapter on an other raspberry system (openplotter) and got the same results. Losing connection, unplugging en plugging resulted in a few minutes connection.
I use another usb wifi dongle and all systems are running :-)
Problem solved. 
Tnx for the feedback
