### ISSUE TITLE
RPi Zero W concurrent AP and Station Mode

### ISSUE THREAD

**Issue by ScruffR** [rudiratlos/hotspot#24]
Is there a way to have a RPi Zero W be the AP but still be connected to my local WiFi network.

For its bigger siblings the bridging between the two networks is simple as they have both eth0 and wlan0 available, but the Zero W only has wlan0 which would need to handle both roles.
Is this at all possible and if so how?

I've seen discussions that state it should be possible but I couldn't get any of them to work (yet)

e.g.
https://raspberrypi.stackexchange.com/questions/63841/rpi-zero-w-as-both-wifi-client-and-access-point

With `hotspot try` I get the message
```
hotspot: PARAM ap_share not set to yes
```
But when I try to use `hotspot modpar hostapd ap_share yes` I do get 
```
change hostaapd ap_share yes (/etc/hostapd/hostapd.conf)
```
But I still don't see the test AP.

**Comment by rudiratlos** [comment]
running station mode and client mode on the same channel (antenna) makes no sense in my opionion.
if you want to use it as a wlan router, use a rpi4 with an additional usb wlan adapter or even use the eth (RJ45) port.

**Comment by ScruffR** [comment]
This may be true for many if not most use-cases but for mine it is a perfectly reasonable approach where anything but a RPi Zero W would be overkill.
I only need to be able to attach a couple of devices to the RPi's own network (with or without public internet connection) while the RPi itself should be publicly accessible whenever it's in reach of a suitable network.

BTW, if this would be an unreasonable use-case, why does the application complain about `ap_share` not being set to `yes`?
How would one get rid of that "error message"?
