### ISSUE TITLE
 [Feature request] Selectable DHCP range and gateway IP for exposed AP

### ISSUE THREAD

**Issue by ScruffR** [rudiratlos/hotspot#25]
I see the default ap0 network on my setup is 10.3.141.0 with the gateway at 10.3.141.1 but I'm not sure whether this will *always* be the case and would prefer if it was possible to have some `modpar` option to set an explicit ip range for that subnet.

**Comment by rudiratlos** [comment]
How about:
hotspot modpar self ap_net 10.4.141

pls. look in line 40 of the hotspot script itself

**Comment by ScruffR** [comment]
Will do, I just didn't find anything in the docs (or overlooked it :blush:)
