### ISSUE TITLE
openvpn is not working 

### ISSUE THREAD

**Issue by flexone1** [rudiratlos/hotspot#26]
Hello,

Unfortunately, openvpn doesn't really work. With my own ovpn file it connects problem free. it also shows me the address of the server. And I get an ip 10.0.8.10 from the server.

Unfortunately, nothing is forwarded after a successful connection. No more connection to the internet.
I always get the error: "iptables Bad rule (does  a matching rule exist in that Chain?)".

The hotspot works fine without openvpn 

What can I do?

**Comment by rudiratlos** [comment]
should work with new version 0.966
