### ISSUE TITLE
Works sporadically

### ISSUE THREAD

**Issue by cleanev** [rudiratlos/hotspot#4]
Hello rudiratlos - 
I love the ease of hotspot and as such started testing.
 with latest version I cannot get iPhone/iPad/notebook to connect to hotspot when started. Removed wpa_pairwise=TKIP line to imitate connection. However after connecting successfully once if I were to reboot RPi and restart hotspot then I keep getting password incorrect error unless I forget the hotspot and start from scratch. 
I have kept your settings as is for testing so everything is pristine as it is from the script. 

Another change I had to make is 
hotspot modpar hostapd country SE
To 
Hotspot modpar hostage country_code SE

Lastly, even though I have enabled iptables and rules do show when I run iptables -S traffic from iPad/iPhone will not get to internet whereas RPi can ping any site - I am using lite version without desktop for my testing

Thank you

**Comment by rudiratlos** [comment]
I've comment in 0.915 that out: wpa_pairwise=TKIP
according to https://www.raspberrypi.org/forums/viewtopic.php?t=157142
