### ISSUE TITLE
how to add openvpn client to this ?

### ISSUE THREAD

**Issue by abeltcb** [rudiratlos/hotspot#5]

**Comment by rudiratlos** [comment]
try version 0.916
just added openvpn

**Comment by abeltcb** [comment]
I try and got this"grep: /etc/hostapd/hostapd.conf: No such file or directory
/usr/local/sbin/hotspot: line 295: [: : integer expression expected
/usr/local/sbin/hotspot: line 298: syntax error near unexpected token `}'
/usr/local/sbin/hotspot: line 298: `}'
"
what went wrong?

**Comment by rudiratlos** [comment]
pls. try again, I had a bug in that release (3days ago). now should be ok.
doc is also updated for openvpn
you have to download (wget) new hotspot release and do hotspot setup again.
setup adds new parameters for openvpn
