### ISSUE TITLE
Wireless channel selection not limited based off of frequency width

### ISSUE THREAD

**Issue by jsn0327** [rudiratlos/hotspot#8]
I've noticed that after adding the following options into my hostapd.conf file, whenever a channel in the 5 ghz range, which has a frequency width of 20 mhz is selected during the auto channel selection phase of the hotspot startup script (such as channel 100, with is a 20 mhz channel), an error is thrown, stating that the selected channel is not in the list of available channels for the WLAN0 interface.  I think that this is because these options require a 5 ghz channel with a 40 mhz frequency width.

ieee80211n=1
require_ht=1
ht_capab=[MAX-AMSDU-3839][HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]

**Comment by rudiratlos** [comment]
you mean, that /etc/hostapd/hostapd.conf just need 3 additional parameters:
wme_enabled=1
require_ht=1
ht_capab=[MAX-AMSDU-3839][HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]

**Comment by jsn0327** [comment]
No, I'm saying that if you want to force a 40mhz channel width so that you get 150mb/s 802.11n speeds as apposed to a 20mhz channel width and 802.11g 54mb/s speeds, you need to add those options to the hostapd.conf. When you do that, certain channels (channel 100 being one of them) that only operate at the 20mhz channel width (not at 40mhz) will still be assigned and an error is thrown stating that "the selected channel is not one of the available channels for the given device" and hostapd will not start. Channels that only operate at the 20mhz channel width need to be omitted from the channel scan that hotspot performs. You can Google 802.11 channels and find out which will operate at the 40mhz width.

**Comment by rudiratlos** [comment]
ok,
in next relase, I will add a parameter to enable/disable the automatic channel find feature.
so you can manually change parameter in hostapd.conf

**Comment by jsn0327** [comment]
That would work. I do like the auto assign function, but it is missing two key features. One is the ability to differentiate between 20mhz and 40mhz channel compatibility, like I previously explained. The other is the ability to only scan for 2.4 channels (channels 1-14) or 5ghz channels (channels 34-165). That way we can broadcast either frequency in AP mode.  Currently, the script just picks a random channel and whichever frequency (2.4 or 5ghz) is associated with that channel is broadcasted.  That severely limits the speed of the access point. This website has alot of good information on the WiFi spec. https://www.electronics-notes.com/articles/connectivity/wifi-ieee-802-11/channels-frequencies-bands-bandwidth.php

I think that the script is great as it currently is, but these little tweaks would make it perfect! Thanks!

**Comment by rudiratlos** [comment]
just uploaded version 0.921. it has 2/5 Ghz filter parmeter. default is for 2GHz Band

**Comment by jsn0327** [comment]
Awesome, thanks a lot! Any chance of getting dual band broadcasting support in the next version? Essentially, start two instances of hostapd, one with a 2.4ghz SSID and the other with a 5ghz SSID? The Pi only supports connection to one or the other at a time, but that would make it easier to choose between the two bands without having to manually change the parameter before starting hotspot. Thanks again for the great work!

**Comment by rudiratlos** [comment]
just uploaded V0.922. FindChannel has more logic to find the best channel. I think there is no need to change parameter for 2/5GHz bands. If multiple free channels are available, FindChan will choose channel number which can be used for 40/80/160Mhz. 
on roadmap for next verson is, to determine channel flags.

**Comment by jsn0327** [comment]
Great, thanks a lot!!
