### ISSUE TITLE
OpenVPN Connection Disconnects and Reconnects Continuously during Reload/Try

### ISSUE THREAD

**Issue by jsn0327** [rudiratlos/hotspot#9]
I noticed that unless I manually stop and restart the openvpn session using 'hotspot ovpn stop' and 'hotspot ovpn start' commands, the openvpn client will connect and disconnect with the server continuously until openvpn is manually stopped.  I think that this is due to a new tunnel being built when issuing the 'hotspot reload' or 'hotspot try' commands without the existing tunnel being taken down.  I noticed that after running those commands, ifconfig listed tun1 and tun2 at the same time.

**Comment by rudiratlos** [comment]
ovpn is currently 'experimental'. I have not tested this feature extensively. 
Do you think that a 'killall openvpn' (scriptline 342) before 'do_ovpn start' (line 344) would fix it?

**Comment by jsn0327** [comment]
Yes. The current tunnel just needs to be brought down before restarting.
